### ISSUE TITLE
Reading from STDIN does not seem to work

### ISSUE THREAD

**Issue by jhthorsen** [browserify/module-deps#64]
I'm trying to pipe data into module-deps but it fails:

```
$ cat robot.js | ./node_modules/.bin/module-deps -

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: path must be a string
    at /home/username/node_modules/module-deps/node_modules/browser-resolve/node_modules/resolve/lib/async.js:15:16
    at process._tickCallback (node.js:419:13)
```

Running module-deps with "robots.js" as input on the other hand works like a charm:

```
$ ./node_modules/.bin/module-deps robot.js 
[
{"file":"/home/username/robot.js","id":"/home/username/robot.js","source":"module.exports = function (s) { return s.toUpperCase() + '!' };\n","deps":{},"entry":true}
]
```

I'm not sure how the output should look when you pipe though... How will it know the path to the entry point? Will it simply have {"file":"-","id":"-",...}

```
$ nodejs --version
v0.10.33
$ npm info module-deps | grep version:
  version: '3.6.4',
```

**Comment by zertosh** [comment]
Weird. I see the option in `cmd.js` but the code looks like it never supported it. I don't think this is a feature worth supporting though. Do you need it for something?

**Comment by ornj** [comment]
I've run into an opportunity where this feature would be helpful. I have a non-node application that is processing a Javascript file through module-deps and I have the contents of the module in memory. 

Probably very much an edge case.

**Comment by zertosh** [comment]
@ornj I think the big blocker for me is figuring out how to support multiple input files, and how to name them. I'd rather not implement stdin support at all if it's going to be half-baked. Any ideas?

**Comment by ornj** [comment]
I haven't really looked into the source very much so my understanding is pretty shallow. Why do they need to be named? What if there is no file on disk?

Browserify reads from stdin, https://github.com/substack/node-browserify/issues/1201#issuecomment-90835972. Maybe some inspiration can be taken from that?

**Comment by zertosh** [comment]
@ornj The file needs to be named because that's how modules are identified. browserify does read stdin and [gives](https://github.com/substack/node-browserify/blob/f7e626ca75bd925a584f9b0fe8ff9d4b8e90f188/index.js#L130-L133) files a default name of `$BASEDIR/_stream_0.js` or what you specify in `--file`. The file doesn't have to exist, it's just a dummy identifier. I guess the same can be done here. Want to submit a PR?

**Comment by ornj** [comment]
I've started to take a look but I'm not a Node dev. I don't have a good environment for debugging Node command line scripts and I'm finding the whole process cumbersome. This doesn't seem like it would be too hard if I could figure out the appropriate place to parse the stream.

As far as supporting multiple files, I don't think that's really necessary. Using @jhthorsen example from above, you're concatenating files so in practice you're really only providing a single file.

**Comment by zertosh** [comment]
@ornj I'll hopefully be merging #96 in the next few days – that'll fix piping to the CLI

**Comment by ornj** [comment]
:+1:

**Comment by jhthorsen** [comment]
Have this issue and the pull request gone stale?

**Comment by jhthorsen** [comment]
Seems to have gone stale.
