### ISSUE TITLE
document output format

### ISSUE THREAD

**Issue by jfirebaugh** [browserify/module-deps#72]
Unless I'm missing something, it appears that the only place the format of the stream's output objects is given is in the example output of example code in the README.

Please document this better: what are the properties on output objects and their meaning?

**Comment by jmm** [comment]
@jfirebaugh Just saw this issue and I agree that the input / output here and throughout the browserify pipeline needs better documentation. See also substack/node-browserify/issues/1162.

If there's something specific you need to know right now I may be able to provide a bit of additional insight as I've looked at this a bit and written a plugin that pushes a stream that follows module-deps.

**Comment by goto-bus-stop** [comment]
added the object shape to the readme here: https://github.com/browserify/module-deps/pull/147
thanks!
